### ISSUE TITLE
will it work for third order categorical features interaction 

### ISSUE THREAD

**Issue by Sandy4321** [scikit-learn-contrib/polylearn#18]
Great code,  thanks !

Plese help to understand
1
will it work for third order categorical features interaction ?
2
will it run on Windows computer ?

3
will it work for sparse data ?

**Comment by vene** [comment]
The answer to all questions is yes. This library supports scipy sparse matrices, and has been tested on windows in the past. (Current CI build is broken on windows because of appveyor syntax changes I think. If you try to build on windows and have issues, please open another issue.)

For 1: all models support degree=3, but the direct solvers do not currently support degree *above* 3.

**Comment by Sandy4321** [comment]
not working for winodws 
opened
https://github.com/scikit-learn-contrib/polylearn/issues/19#issuecomment-934777062
